package uat

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/adrg/frontmatter"
	"gopkg.in/yaml.v3"
)

// UATSummary holds aggregate pass/fail/skip counts for a UAT run.
type UATSummary struct {
	Total int `yaml:"total"`
	Pass  int `yaml:"pass"`
	Fail  int `yaml:"fail"`
	Skip  int `yaml:"skip"`
}

// UATItem represents a single UAT test item.
type UATItem struct {
	ID          string `yaml:"id"`
	Description string `yaml:"description"`
	Status      string `yaml:"status"` // "pending" / "pass" / "fail" / "skip"
	Notes       string `yaml:"notes,omitempty"`
	RunAt       string `yaml:"run_at,omitempty"` // RFC3339 timestamp
}

// UATRunResult captures a single UAT run's summary and timestamp.
type UATRunResult struct {
	RunAt   string     `yaml:"run_at"`
	Summary UATSummary `yaml:"summary"`
}

// UATChecklist is the complete UAT checklist stored in a .mysd/uat/{change}-uat.md file.
type UATChecklist struct {
	SpecVersion string         `yaml:"spec-version"`
	Change      string         `yaml:"change"`
	Generated   string         `yaml:"generated"`
	LastRun     string         `yaml:"last_run,omitempty"`
	Summary     UATSummary     `yaml:"summary"`
	Results     []UATItem      `yaml:"results"`
	RunHistory  []UATRunResult `yaml:"run_history,omitempty"`
}

// NewUATChecklist creates a new UATChecklist for the given change name and items.
// All items default to "pending" status. IDs are assigned as "uat-1", "uat-2", etc.
func NewUATChecklist(changeName string, items []UATItem) UATChecklist {
	results := make([]UATItem, len(items))
	for i, item := range items {
		results[i] = item
		if results[i].ID == "" {
			results[i].ID = fmt.Sprintf("uat-%d", i+1)
		}
		if results[i].Status == "" {
			results[i].Status = "pending"
		}
	}

	return UATChecklist{
		SpecVersion: "1",
		Change:      changeName,
		Generated:   time.Now().Format(time.RFC3339),
		Summary: UATSummary{
			Total: len(items),
		},
		Results: results,
	}
}

// UATFilePath returns the canonical file path for a UAT checklist.
// Format: {baseDir}/.mysd/uat/{changeName}-uat.md
func UATFilePath(baseDir, changeName string) string {
	return filepath.Join(baseDir, ".mysd", "uat", changeName+"-uat.md")
}

// WriteUAT writes the UAT checklist to filePath in YAML frontmatter + markdown body format.
// If the file already exists, the current results are appended to run_history (Pitfall 4 prevention).
// The .mysd/uat/ directory is created if it does not exist.
func WriteUAT(filePath string, checklist UATChecklist) error {
	if err := os.MkdirAll(filepath.Dir(filePath), 0755); err != nil {
		return fmt.Errorf("create uat directory: %w", err)
	}

	// History preservation: if file exists, read existing data and append current results to run_history.
	if _, statErr := os.Stat(filePath); statErr == nil {
		existing, readErr := ReadUAT(filePath)
		if readErr == nil && existing.Change != "" {
			// Append the existing results as a run_history entry.
			if existing.Summary.Total > 0 || existing.LastRun != "" {
				runAt := existing.LastRun
				if runAt == "" {
					runAt = existing.Generated
				}
				historyEntry := UATRunResult{
					RunAt:   runAt,
					Summary: existing.Summary,
				}
				checklist.RunHistory = append(existing.RunHistory, historyEntry)
			} else {
				checklist.RunHistory = existing.RunHistory
			}
		}
	}

	// Update last_run timestamp.
	checklist.LastRun = time.Now().Format(time.RFC3339)

	// Marshal YAML frontmatter.
	yamlBytes, err := yaml.Marshal(checklist)
	if err != nil {
		return fmt.Errorf("marshal UAT frontmatter: %w", err)
	}

	// Build the file content.
	var sb strings.Builder
	sb.WriteString("---\n")
	sb.Write(yamlBytes)
	sb.WriteString("---\n")

	// Markdown body.
	sb.WriteString(fmt.Sprintf("\n## UAT Checklist: %s\n\n", checklist.Change))
	sb.WriteString("_Generated by mysd verify. Run `/mysd:uat` to conduct acceptance testing._\n\n")
	sb.WriteString("### UI Acceptance Tests\n\n")
	for _, item := range checklist.Results {
		sb.WriteString(fmt.Sprintf("- [ ] %s\n", item.Description))
	}

	return os.WriteFile(filePath, []byte(sb.String()), 0644)
}

// ReadUAT reads a UAT checklist file and returns the parsed UATChecklist.
// If the file does not exist, a zero-value UATChecklist is returned without error.
// This enables first-time use without requiring a pre-existing file.
func ReadUAT(filePath string) (UATChecklist, error) {
	f, err := os.Open(filePath)
	if err != nil {
		if os.IsNotExist(err) {
			return UATChecklist{}, nil
		}
		return UATChecklist{}, fmt.Errorf("open UAT file: %w", err)
	}
	defer f.Close()

	var cl UATChecklist
	_, parseErr := frontmatter.Parse(f, &cl)
	if parseErr != nil {
		return UATChecklist{}, fmt.Errorf("parse UAT frontmatter: %w", parseErr)
	}

	return cl, nil
}
